<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <_ProjectFileVersion>10.0.30319.1</_ProjectFileVersion>
    <FB_STATIC_PREPROCESSOR_DEFINITIONS>STATIC_CLIENT</FB_STATIC_PREPROCESSOR_DEFINITIONS>
    <FB_STATIC_PREPROCESSOR_DEFINITIONS Condition="'$(FBBUILD_WITHOUT_TOMCRYPT)'=='1'">STATIC_CLIENT;WITHOUT_TOMCRYPT</FB_STATIC_PREPROCESSOR_DEFINITIONS>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <PreprocessorDefinitions>$(FB_STATIC_PREPROCESSOR_DEFINITIONS);%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <RuntimeLibrary>MultiThreadedDebugDLL</RuntimeLibrary>
      <BasicRuntimeChecks>EnableFastChecks</BasicRuntimeChecks>
    </ClCompile>
    <ResourceCompile>
      <PreprocessorDefinitions>_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ResourceCompile>
  </ItemDefinitionGroup>
</Project>
